// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/4/10 23:12:54
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Nuxt-React-game-platform/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Nuxt-React-game-platform/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Nuxt-React-game-platform/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Nuxt-React-game-platform/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Nuxt-React-game-platform/plugins/**/*.{js,ts,mjs}","D:/Nuxt-React-game-platform/composables/**/*.{js,ts,mjs}","D:/Nuxt-React-game-platform/utils/**/*.{js,ts,mjs}","D:/Nuxt-React-game-platform/pages/index.vue","D:/Nuxt-React-game-platform/pages/forum/index.vue","D:/Nuxt-React-game-platform/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Nuxt-React-game-platform/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Nuxt-React-game-platform/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;